import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://www.jjlawohio.com';

  const d = {
    home: new Date('2026-03-10'),
    blog: new Date('2026-03-10'),
    attorneys: new Date('2026-02-15'),
    service: new Date('2026-03-16'),
    court: new Date('2026-03-16'),
    location: new Date('2026-03-16'),
  };

  const routes = [
    // Main pages
    { url: '', priority: 1.0, changeFrequency: 'weekly' as const, lastModified: d.home },
    { url: '/contact', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.home },
    { url: '/services', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/about', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.attorneys },
    { url: '/about/legal-assistant', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.attorneys },
    
    // Our Law Firm
    { url: '/our-law-firm', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.home },
    { url: '/our-law-firm/about-us', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.attorneys },
    { url: '/our-law-firm/our-attorneys', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.attorneys },
    { url: '/our-law-firm/our-attorneys/raneem-ali', priority: 0.6, changeFrequency: 'monthly' as const, lastModified: d.attorneys },
    { url: '/our-law-firm/our-attorneys/jonathan-cowan', priority: 0.6, changeFrequency: 'monthly' as const, lastModified: d.attorneys },
    { url: '/our-law-firm/our-attorneys/layan-khairi', priority: 0.6, changeFrequency: 'monthly' as const, lastModified: d.attorneys },
    { url: '/our-law-firm/our-attorneys/mateo-improvola', priority: 0.6, changeFrequency: 'monthly' as const, lastModified: d.attorneys },
    { url: '/our-law-firm/case-results', priority: 0.7, changeFrequency: 'weekly' as const, lastModified: d.blog },
    { url: '/our-law-firm/document-templates', priority: 0.6, changeFrequency: 'monthly' as const, lastModified: d.blog },
    { url: '/our-law-firm/blog', priority: 0.8, changeFrequency: 'weekly' as const, lastModified: d.blog },
    { url: '/our-law-firm/blog/what-to-do-pulled-over-ovi-ohio', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-01-15') },
    { url: '/our-law-firm/blog/ohio-castle-doctrine-self-defense-laws', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-01-20') },
    { url: '/our-law-firm/blog/steps-after-car-accident-ohio', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-01-25') },
    { url: '/our-law-firm/blog/ohio-new-expungement-laws-clear-record', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-02-01') },
    { url: '/our-law-firm/blog/starting-business-ohio-llc-vs-corporation', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-02-05') },
    { url: '/our-law-firm/blog/what-to-expect-first-court-appearance-ohio', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-02-10') },
    { url: '/our-law-firm/blog/ohio-slip-and-fall-laws-property-owners', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-02-12') },
    { url: '/our-law-firm/blog/protecting-rights-during-traffic-stop-ohio', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-02-15') },
    { url: '/our-law-firm/blog/limited-driving-privileges-after-ovi-ohio', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-02-18') },
    { url: '/our-law-firm/blog/ohio-als-appeal-30-day-deadline', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-02-20') },
    { url: '/our-law-firm/blog/dog-bite-laws-ohio-owner-liability', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-02-22') },
    { url: '/our-law-firm/blog/landlord-duty-repair-ohio-tenant-rights', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-02-24') },
    { url: '/our-law-firm/blog/forming-llc-ohio-step-by-step', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-02-26') },
    { url: '/our-law-firm/blog/what-is-revocable-living-trust', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-02-28') },
    { url: '/our-law-firm/blog/first-dui-ohio-will-i-go-to-jail', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-03-01') },
    { url: '/our-law-firm/blog/how-much-does-dui-cost-ohio', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-03-02') },
    { url: '/our-law-firm/blog/charged-with-assault-what-happens-next', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-03-03') },
    { url: '/our-law-firm/blog/shoplifting-ohio-first-offense', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-03-04') },
    { url: '/our-law-firm/blog/slipped-fell-at-store-can-i-sue', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-03-05') },
    { url: '/our-law-firm/blog/how-long-sue-after-injury-ohio', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-03-06') },
    { url: '/our-law-firm/blog/landlord-wont-fix-heat-repairs-ohio', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-03-07') },
    { url: '/our-law-firm/blog/do-i-need-will-ohio', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-03-08') },
    { url: '/our-law-firm/blog/do-i-need-llc-for-business', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-03-09') },
    { url: '/our-law-firm/blog/will-vs-trust-ohio', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-03-10') },
    { url: '/our-law-firm/blog/ohio-probate-process-step-by-step', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-03-16') },
    { url: '/our-law-firm/blog/what-is-expungement-ohio-2024', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-03-17') },
    { url: '/our-law-firm/blog/ohio-business-formation-llc-vs-corp', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-03-18') },
    { url: '/our-law-firm/blog/personal-injury-ohio-statute-of-limitations', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-03-19') },
    { url: '/our-law-firm/blog/ohio-landlord-tenant-security-deposit-laws', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-03-20') },
    { url: '/our-law-firm/blog/misdemeanor-vs-felony-ohio', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-03-21') },
    { url: '/our-law-firm/blog/ohio-power-of-attorney-guide', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-03-22') },
    { url: '/our-law-firm/blog/what-happens-after-ovi-arrest-ohio', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-03-23') },
    { url: '/our-law-firm/blog/ohio-civil-protection-order-guide', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-03-24') },
    { url: '/our-law-firm/blog/starting-ohio-nonprofit-organization', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: new Date('2026-03-25') },

    // Criminal Defense
    { url: '/criminal-defense', priority: 0.9, changeFrequency: 'weekly' as const, lastModified: d.service },
    { url: '/criminal-defense/assault-charges', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/domestic-violence', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/criminal-mischief', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/criminal-damaging', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/criminal-trespass', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/petty-theft', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/resisting-arrest', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/obstruction-of-official-business', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/speeding-tickets', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/driving-under-suspension', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/no-operators-license', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/expungement-record-sealing', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },

    // OVI/DUI Defense
    { url: '/ovi-dui-defense', priority: 0.9, changeFrequency: 'weekly' as const, lastModified: d.service },
    { url: '/ovi-dui-defense/first-ovi', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/ovi-dui-defense/second-ovi', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/ovi-dui-defense/third-ovi', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/ovi-dui-defense/high-tier-ovi', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/ovi-dui-defense/refusal-ovi', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/ovi-dui-defense/underage-ovi', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/ovi-dui-defense/commercial-dui-cdl', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/ovi-dui-defense/ovi-with-accident', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/ovi-dui-defense/driving-under-ovi-suspension', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/ovi-dui-defense/limited-driving-privileges', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },

    // Personal Injury
    { url: '/personal-injury', priority: 0.9, changeFrequency: 'weekly' as const, lastModified: d.service },
    { url: '/personal-injury/car-accidents', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/personal-injury/truck-accidents', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/personal-injury/motorcycle-accidents', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/personal-injury/pedestrian-accidents', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/personal-injury/slip-and-fall', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/personal-injury/premises-liability', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/personal-injury/dog-bites', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/personal-injury/medical-malpractice', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/personal-injury/nursing-home-abuse', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/personal-injury/workplace-injuries', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/personal-injury/wrongful-death', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/personal-injury/catastrophic-injuries', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },

    // Civil
    { url: '/civil', priority: 0.9, changeFrequency: 'weekly' as const, lastModified: d.service },
    { url: '/civil/breach-of-contract', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/civil/real-estate-disputes', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/civil/landlord-tenant-disputes', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/civil/evictions', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/civil/construction-disputes', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/civil/debt-collection-defense', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/civil/employment-disputes', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/civil/defamation', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/civil/civil-protection-orders', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/civil/appeals', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },

    // Business
    { url: '/business', priority: 0.9, changeFrequency: 'weekly' as const, lastModified: d.service },
    { url: '/business/business-formation', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/business/llc-formation', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/business/contract-drafting-review', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/business/business-litigation', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/business/partnership-disputes', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/business/shareholder-disputes', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/business/non-compete-agreements', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/business/employment-agreements', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/business/business-compliance', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/business/business-dissolution', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },

    // Other Services
    { url: '/other-services', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/other-services/estate-planning', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/other-services/estate-planning-wills', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/other-services/powers-of-attorney', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/other-services/guardianships', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/other-services/probate', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/other-services/probate-administration', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/other-services/will-contests', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/other-services/estate-disputes', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/other-services/dispute-resolution', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/other-services/mediation', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/other-services/arbitration', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },

    // Trusts
    { url: '/trusts', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/trusts/revocable-living-trusts', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/trusts/irrevocable-life-insurance-trusts', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/trusts/special-needs-trusts', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/trusts/dynasty-trusts', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/trusts/charitable-trusts', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/trusts/spendthrift-trusts', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/trusts/medicaid-asset-protection-trusts', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/trusts/land-trusts', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/trusts/qtip-trusts', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/trusts/irrevocable-trusts', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/trusts/asset-protection-trusts', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },

    // Courts
    { url: '/courts', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/franklin-county', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/franklin-county-municipal-court', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/delaware-county', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/delaware-county-municipal-court', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/pickaway-county', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/circleville-municipal-court', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/athens-county', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/athens-municipal-court', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/morrow-county', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/morrow-county-municipal-court', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/clinton-county', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/wilmington-municipal-court', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/butler-county', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/hamilton-municipal-court', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/greene-county', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/fairborn-municipal-court', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/montgomery-county', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/dayton-municipal-court', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },

    // Location Pages
    { url: '/locations/pickaway-county/ovi-dui-defense-circleville-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/pickaway-county/criminal-misdemeanor-defense-circleville-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/athens-county/ovi-dui-defense-athens-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/athens-county/criminal-misdemeanor-defense-athens-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/morrow-county/ovi-dui-defense-morrow-county-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/morrow-county/criminal-misdemeanor-defense-morrow-county-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/morrow-county/personal-injury-morrow-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/morrow-county/business-formation-llc-morrow-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/athens-county/personal-injury-athens-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/athens-county/business-formation-llc-athens-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/pickaway-county/personal-injury-pickaway-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/pickaway-county/business-formation-llc-pickaway-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/personal-injury-franklin-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/business-formation-llc-franklin-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/delaware-county/ovi-dui-defense-delaware-county-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/delaware-county/personal-injury-delaware-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/delaware-county/business-formation-llc-delaware-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/delaware-county/criminal-misdemeanor-defense-delaware-county-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/butler-county/ovi-dui-defense-butler-county-area-courts', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/butler-county/personal-injury-butler-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/butler-county/business-formation-llc-butler-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/butler-county/criminal-misdemeanor-defense-butler-county-area-courts', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/greene-county/ovi-dui-defense-greene-county-fairborn-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/greene-county/personal-injury-greene-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/greene-county/business-formation-llc-greene-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/greene-county/criminal-misdemeanor-defense-greene-county-fairborn-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/montgomery-county/ovi-dui-defense-montgomery-county-dayton-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/montgomery-county/personal-injury-montgomery-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/montgomery-county/business-formation-llc-montgomery-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/montgomery-county/criminal-misdemeanor-defense-montgomery-county-dayton-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/clinton-county/ovi-dui-defense-clinton-county-wilmington-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/clinton-county/personal-injury-clinton-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/clinton-county/business-formation-llc-clinton-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/clinton-county/criminal-misdemeanor-defense-clinton-county-wilmington-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
  ];

  return routes.map((route) => ({
    url: `${baseUrl}${route.url}`,
    lastModified: route.lastModified,
    changeFrequency: route.changeFrequency,
    priority: route.priority,
  }));
}
