import { MetadataRoute } from 'next';
import { blogPosts } from '@/data/blog-posts';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://www.jjlawohio.com';

  const d = {
    home: new Date('2026-06-24'),
    blog: new Date('2026-06-24'),
    attorneys: new Date('2026-06-24'),
    service: new Date('2026-06-24'),
    court: new Date('2026-06-24'),
    location: new Date('2026-06-24'),
  };

  // Dynamically generate blog post sitemap entries from data
  const blogRoutes = blogPosts.map((post) => ({
    url: `/our-law-firm/blog/${post.slug}`,
    priority: 0.7,
    changeFrequency: 'monthly' as const,
    lastModified: new Date(post.date),
  }));

  const routes = [
    // Main pages
    { url: '', priority: 1.0, changeFrequency: 'weekly' as const, lastModified: d.home },
    { url: '/contact', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.home },
    { url: '/services', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/about', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.attorneys },
    { url: '/about/legal-assistant', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.attorneys },
    { url: '/privacy', priority: 0.3, changeFrequency: 'yearly' as const, lastModified: d.home },

    // Our Law Firm
    { url: '/our-law-firm', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.home },
    { url: '/our-law-firm/about-us', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.attorneys },
    { url: '/our-law-firm/our-attorneys', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.attorneys },
    { url: '/our-law-firm/our-attorneys/raneem-ali', priority: 0.6, changeFrequency: 'monthly' as const, lastModified: d.attorneys },
    { url: '/our-law-firm/our-attorneys/jonathan-cowan', priority: 0.6, changeFrequency: 'monthly' as const, lastModified: d.attorneys },
    { url: '/our-law-firm/our-attorneys/mateo-improvola', priority: 0.6, changeFrequency: 'monthly' as const, lastModified: d.attorneys },
    { url: '/our-law-firm/case-results', priority: 0.7, changeFrequency: 'weekly' as const, lastModified: d.blog },
    { url: '/our-law-firm/document-templates', priority: 0.6, changeFrequency: 'monthly' as const, lastModified: d.blog },
    { url: '/our-law-firm/blog', priority: 0.8, changeFrequency: 'weekly' as const, lastModified: d.blog },
    ...blogRoutes,

    // Criminal Defense
    { url: '/criminal-defense', priority: 0.9, changeFrequency: 'weekly' as const, lastModified: d.service },
    { url: '/criminal-defense/assault-charges', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/domestic-violence', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/criminal-mischief', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/criminal-damaging', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/criminal-trespass', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/petty-theft', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/resisting-arrest', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/obstruction-of-official-business', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/speeding-tickets', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/driving-under-suspension', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/no-operators-license', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/expungement-record-sealing', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/disorderly-conduct', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/drug-possession', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/marijuana-possession', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/criminal-defense/open-container', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },

    // OVI/DUI Defense
    { url: '/ovi-dui-defense', priority: 0.9, changeFrequency: 'weekly' as const, lastModified: d.service },
    { url: '/ovi-dui-defense/first-ovi', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/ovi-dui-defense/second-ovi', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/ovi-dui-defense/third-ovi', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/ovi-dui-defense/high-tier-ovi', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/ovi-dui-defense/refusal-ovi', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/ovi-dui-defense/underage-ovi', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/ovi-dui-defense/commercial-dui-cdl', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/ovi-dui-defense/ovi-with-accident', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/ovi-dui-defense/driving-under-ovi-suspension', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/ovi-dui-defense/limited-driving-privileges', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },

    // Personal Injury
    { url: '/personal-injury', priority: 0.9, changeFrequency: 'weekly' as const, lastModified: d.service },
    { url: '/personal-injury/car-accidents', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/personal-injury/truck-accidents', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/personal-injury/motorcycle-accidents', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/personal-injury/pedestrian-accidents', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/personal-injury/slip-and-fall', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/personal-injury/premises-liability', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/personal-injury/dog-bites', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/personal-injury/medical-malpractice', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/personal-injury/nursing-home-abuse', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/personal-injury/workplace-injuries', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/personal-injury/wrongful-death', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/personal-injury/catastrophic-injuries', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },

    // Civil
    { url: '/civil', priority: 0.9, changeFrequency: 'weekly' as const, lastModified: d.service },
    { url: '/civil/breach-of-contract', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/civil/real-estate-disputes', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/civil/landlord-tenant-disputes', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/civil/evictions', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/civil/construction-disputes', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/civil/debt-collection-defense', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/civil/employment-disputes', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/civil/defamation', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/civil/civil-protection-orders', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/civil/appeals', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },

    // Business
    { url: '/business', priority: 0.9, changeFrequency: 'weekly' as const, lastModified: d.service },
    { url: '/business/business-formation', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/business/llc-formation', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/business/contract-drafting-review', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/business/business-litigation', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/business/partnership-disputes', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/business/shareholder-disputes', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/business/non-compete-agreements', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/business/employment-agreements', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/business/business-compliance', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/business/business-dissolution', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },

    // Other Services
    { url: '/other-services', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/other-services/estate-planning', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/other-services/estate-planning-wills', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/other-services/powers-of-attorney', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/other-services/guardianships', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/other-services/probate', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/other-services/probate-administration', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/other-services/will-contests', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/other-services/estate-disputes', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/other-services/dispute-resolution', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/other-services/mediation', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/other-services/arbitration', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },

    // Trusts
    { url: '/trusts', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/trusts/revocable-living-trusts', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/trusts/irrevocable-life-insurance-trusts', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/trusts/special-needs-trusts', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/trusts/dynasty-trusts', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/trusts/charitable-trusts', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/trusts/spendthrift-trusts', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/trusts/medicaid-asset-protection-trusts', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/trusts/land-trusts', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/trusts/qtip-trusts', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/trusts/irrevocable-trusts', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },
    { url: '/trusts/asset-protection-trusts', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.service },

    // Courts
    { url: '/courts', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/franklin-county', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/franklin-county-municipal-court', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/delaware-county', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/delaware-county-municipal-court', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/pickaway-county', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/circleville-municipal-court', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/athens-county', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/athens-municipal-court', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/morrow-county', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/morrow-county-municipal-court', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/clinton-county', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/wilmington-municipal-court', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/butler-county', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/hamilton-municipal-court', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/greene-county', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/fairborn-municipal-court', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/montgomery-county', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },
    { url: '/courts/dayton-municipal-court', priority: 0.7, changeFrequency: 'monthly' as const, lastModified: d.court },

    // Location Pages
    { url: '/locations/pickaway-county/ovi-dui-defense-circleville-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/pickaway-county/criminal-misdemeanor-defense-circleville-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/athens-county/ovi-dui-defense-athens-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/athens-county/criminal-misdemeanor-defense-athens-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/morrow-county/ovi-dui-defense-morrow-county-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/morrow-county/criminal-misdemeanor-defense-morrow-county-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/morrow-county/personal-injury-morrow-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/morrow-county/business-formation-llc-morrow-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/athens-county/personal-injury-athens-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/athens-county/business-formation-llc-athens-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/pickaway-county/personal-injury-pickaway-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/pickaway-county/business-formation-llc-pickaway-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/personal-injury-franklin-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/business-formation-llc-franklin-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    // Franklin County Columbus city pages
    { url: '/locations/franklin-county/ovi-dui-defense-columbus', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/first-ovi-columbus', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/second-ovi-columbus', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/third-ovi-columbus', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/felony-ovi-columbus', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/underage-ovi-columbus', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/cdl-ovi-columbus', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/refusal-ovi-columbus', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/high-tier-ovi-columbus', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/ovi-with-accident-columbus', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/marijuana-ovi-columbus', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/domestic-violence-defense-columbus', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/theft-defense-columbus', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/expungement-columbus', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/drug-possession-defense-columbus', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/assault-defense-columbus', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/marijuana-possession-columbus', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/disorderly-conduct-defense-columbus', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/open-container-defense-columbus', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/expungement-franklin-county', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/mayors-courts-franklin-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    // Franklin County Municipal Court pages
    { url: '/locations/franklin-county/criminal-misdemeanor-defense-franklin-county-municipal-court', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/ovi-dui-defense-franklin-county-municipal-court', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.location },
    // Franklin County suburb pages — Bexley
    { url: '/locations/franklin-county/ovi-dui-defense-bexley', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/theft-defense-bexley', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/domestic-violence-defense-bexley', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/assault-defense-bexley', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/drug-possession-defense-bexley', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/disorderly-conduct-defense-bexley', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/open-container-defense-bexley', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/mayors-court-bexley', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    // Canal Winchester
    { url: '/locations/franklin-county/ovi-dui-defense-canal-winchester', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/theft-defense-canal-winchester', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/domestic-violence-defense-canal-winchester', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/assault-defense-canal-winchester', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/drug-possession-defense-canal-winchester', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/disorderly-conduct-defense-canal-winchester', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/open-container-defense-canal-winchester', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/mayors-court-canal-winchester', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    // Dublin
    { url: '/locations/franklin-county/ovi-dui-defense-dublin', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/theft-defense-dublin', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/domestic-violence-defense-dublin', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/assault-defense-dublin', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/drug-possession-defense-dublin', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/disorderly-conduct-defense-dublin', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/open-container-defense-dublin', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/mayors-court-dublin', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    // Grandview Heights (no mayor's court)
    { url: '/locations/franklin-county/ovi-dui-defense-grandview-heights', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/theft-defense-grandview-heights', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/domestic-violence-defense-grandview-heights', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/assault-defense-grandview-heights', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/drug-possession-defense-grandview-heights', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/disorderly-conduct-defense-grandview-heights', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/open-container-defense-grandview-heights', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    // Grove City
    { url: '/locations/franklin-county/ovi-dui-defense-grove-city', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/theft-defense-grove-city', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/domestic-violence-defense-grove-city', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/assault-defense-grove-city', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/drug-possession-defense-grove-city', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/disorderly-conduct-defense-grove-city', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/open-container-defense-grove-city', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/mayors-court-grove-city', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    // Groveport
    { url: '/locations/franklin-county/ovi-dui-defense-groveport', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/theft-defense-groveport', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/domestic-violence-defense-groveport', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/assault-defense-groveport', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/drug-possession-defense-groveport', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/disorderly-conduct-defense-groveport', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/open-container-defense-groveport', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/mayors-court-groveport', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    // Hilliard
    { url: '/locations/franklin-county/ovi-dui-defense-hilliard', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/theft-defense-hilliard', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/domestic-violence-defense-hilliard', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/assault-defense-hilliard', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/drug-possession-defense-hilliard', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/disorderly-conduct-defense-hilliard', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/open-container-defense-hilliard', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/mayors-court-hilliard', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    // Marble Cliff (no mayor's court)
    { url: '/locations/franklin-county/ovi-dui-defense-marble-cliff', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/theft-defense-marble-cliff', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/domestic-violence-defense-marble-cliff', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/assault-defense-marble-cliff', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/drug-possession-defense-marble-cliff', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/disorderly-conduct-defense-marble-cliff', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/open-container-defense-marble-cliff', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    // New Albany
    { url: '/locations/franklin-county/ovi-dui-defense-new-albany', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/theft-defense-new-albany', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/domestic-violence-defense-new-albany', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/assault-defense-new-albany', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/drug-possession-defense-new-albany', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/disorderly-conduct-defense-new-albany', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/open-container-defense-new-albany', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    // Obetz
    { url: '/locations/franklin-county/ovi-dui-defense-obetz', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/theft-defense-obetz', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/domestic-violence-defense-obetz', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/assault-defense-obetz', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/drug-possession-defense-obetz', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/disorderly-conduct-defense-obetz', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/open-container-defense-obetz', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/mayors-court-obetz', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    // Pickerington
    { url: '/locations/franklin-county/ovi-dui-defense-pickerington', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/theft-defense-pickerington', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/domestic-violence-defense-pickerington', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/assault-defense-pickerington', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/drug-possession-defense-pickerington', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/disorderly-conduct-defense-pickerington', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/open-container-defense-pickerington', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/mayors-court-pickerington', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    // Reynoldsburg
    { url: '/locations/franklin-county/ovi-dui-defense-reynoldsburg', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/theft-defense-reynoldsburg', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/domestic-violence-defense-reynoldsburg', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/assault-defense-reynoldsburg', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/drug-possession-defense-reynoldsburg', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/disorderly-conduct-defense-reynoldsburg', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/open-container-defense-reynoldsburg', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/mayors-court-reynoldsburg', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    // Upper Arlington
    { url: '/locations/franklin-county/ovi-dui-defense-upper-arlington', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/theft-defense-upper-arlington', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/domestic-violence-defense-upper-arlington', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/assault-defense-upper-arlington', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/drug-possession-defense-upper-arlington', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/disorderly-conduct-defense-upper-arlington', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/open-container-defense-upper-arlington', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/mayors-court-upper-arlington', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    // Westerville
    { url: '/locations/franklin-county/ovi-dui-defense-westerville', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/theft-defense-westerville', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/domestic-violence-defense-westerville', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/assault-defense-westerville', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/drug-possession-defense-westerville', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/disorderly-conduct-defense-westerville', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/open-container-defense-westerville', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/mayors-court-westerville', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    // Whitehall
    { url: '/locations/franklin-county/ovi-dui-defense-whitehall', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/theft-defense-whitehall', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/domestic-violence-defense-whitehall', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/assault-defense-whitehall', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/drug-possession-defense-whitehall', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/disorderly-conduct-defense-whitehall', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/open-container-defense-whitehall', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/mayors-court-whitehall', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    // Worthington
    { url: '/locations/franklin-county/ovi-dui-defense-worthington', priority: 0.9, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/theft-defense-worthington', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/domestic-violence-defense-worthington', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/assault-defense-worthington', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/drug-possession-defense-worthington', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/disorderly-conduct-defense-worthington', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/open-container-defense-worthington', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/franklin-county/mayors-court-worthington', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/delaware-county/ovi-dui-defense-delaware-county-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/delaware-county/personal-injury-delaware-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/delaware-county/business-formation-llc-delaware-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/delaware-county/criminal-misdemeanor-defense-delaware-county-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/butler-county/ovi-dui-defense-butler-county-area-courts', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/butler-county/personal-injury-butler-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/butler-county/business-formation-llc-butler-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/butler-county/criminal-misdemeanor-defense-butler-county-area-courts', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/greene-county/ovi-dui-defense-greene-county-fairborn-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/greene-county/personal-injury-greene-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/greene-county/business-formation-llc-greene-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/greene-county/criminal-misdemeanor-defense-greene-county-fairborn-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/montgomery-county/ovi-dui-defense-montgomery-county-dayton-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/montgomery-county/personal-injury-montgomery-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/montgomery-county/business-formation-llc-montgomery-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/montgomery-county/criminal-misdemeanor-defense-montgomery-county-dayton-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/clinton-county/ovi-dui-defense-clinton-county-wilmington-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/clinton-county/personal-injury-clinton-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/clinton-county/business-formation-llc-clinton-county', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
    { url: '/locations/clinton-county/criminal-misdemeanor-defense-clinton-county-wilmington-municipal-court', priority: 0.8, changeFrequency: 'monthly' as const, lastModified: d.location },
  ];

  return routes.map((route) => ({
    url: `${baseUrl}${route.url}`,
    lastModified: route.lastModified,
    changeFrequency: route.changeFrequency,
    priority: route.priority,
  }));
}
