import { Metadata } from 'next';
import Link from 'next/link';
import PageHero from '@/components/PageHero';
import Breadcrumbs from '@/components/Breadcrumbs';
import FAQ from '@/components/FAQ';
import ContactCTA from '@/components/ContactCTA';
import LocationsWeServe from '@/components/LocationsWeServe';

export const metadata: Metadata = {
  title: 'Medicaid Asset Protection Trusts Ohio',
  description: 'Ohio Medicaid Asset Protection Trust attorney helping Columbus, Cincinnati, and Dayton families protect assets from Medicaid spend-down.',
  keywords: [
    'medicaid asset protection trust Columbus OH',
    'MAPT attorney Ohio',
    'medicaid planning attorney Ohio',
    'medicaid 5-year lookback Ohio',
    'Ohio Medicaid estate recovery ORC 5163.21',
    'income-only trust Ohio',
    'protect home from Medicaid Ohio',
    'Medicaid spend-down planning Ohio',
    'Miller trust Ohio QIT',
    'long-term care planning Columbus OH',
  ],
  openGraph: {
    title: 'Medicaid Asset Protection Trusts Ohio',
    url: 'https://www.jjlawohio.com/trusts/medicaid-asset-protection-trusts',
    images: [{ url: '/assets/Jwayyed_Logo_Inverted.JPEG', width: 1200, height: 630, alt: 'Jwayyed Law LLC' }],
    },
  alternates: { canonical: '/trusts/medicaid-asset-protection-trusts' },
};

const breadcrumbItems = [
  { label: 'Trusts', href: '/trusts' },
  { label: 'Medicaid Asset Protection Trusts', href: '/trusts/medicaid-asset-protection-trusts' },
];

const faqs = [
  {
    question: `What is a Medicaid Asset Protection Trust (MAPT)?`,
    answer: `A Medicaid Asset Protection Trust (MAPT) is an irrevocable trust into which you transfer assets — often your home, savings, or investment accounts — for the purpose of eventually qualifying for Ohio Medicaid long-term care benefits. Because you cannot be a beneficiary of the trust's principal (you give up the right to get those assets back), the assets transferred to the trust are no longer "countable resources" for Medicaid eligibility purposes after the five-year lookback period has passed. The trust is typically structured as an income-only trust: you may receive income generated by the trust assets, but you cannot access the principal.`,
  },
  {
    question: `How does Ohio's five-year Medicaid lookback work?`,
    answer: `Under 42 U.S.C. 1396p, Ohio Medicaid reviews all asset transfers made within 60 months (five years) of a Medicaid application for long-term care services. If you transferred assets to a MAPT within that five-year window, Ohio will treat the transferred assets as if you still own them for the purpose of calculating your eligibility. A transfer penalty is imposed — a period of Medicaid ineligibility calculated by dividing the value of the transferred assets by Ohio's average monthly nursing facility cost (approximately $9,000–$10,000 per month in 2024). The penalty period does not start until you are otherwise eligible for Medicaid but for the transferred assets, which can create a dangerous gap in coverage if transfers are made too close to the application.`,
  },
  {
    question: `Can I keep my house if I establish a MAPT?`,
    answer: `Many Ohio clients establish a MAPT specifically to protect their home. Your primary residence is an exempt asset for Medicaid eligibility purposes while you are living there or while your spouse lives there. However, Ohio Medicaid estate recovery under ORC 5163.21 allows the state to recoup Medicaid costs from your probate estate after you die — which can include a lien on your home if it passes through probate. By transferring your home to a MAPT more than five years before applying for Medicaid, you remove it from both your countable resources and your probate estate, protecting it from estate recovery for your heirs. This is one of the most valuable MAPT strategies for Ohio homeowners.`,
  },
  {
    question: `What happens if I need Medicaid before the five-year lookback period has passed?`,
    answer: `If you apply for Medicaid before five years have passed since you funded the MAPT, the transferred assets will trigger a penalty period of Medicaid ineligibility. During that gap, you must pay for care privately. This is why Medicaid planning should be done well in advance of an anticipated need — ideally 5 to 10 years before long-term care is needed. If an unexpected health crisis forces an early application, an elder law attorney can sometimes use other strategies (such as converting countable assets to exempt assets, or using an immediate annuity to "spend down" in a compliant way) to minimize or bridge the penalty period.`,
  },
  {
    question: `Who should serve as trustee of a MAPT?`,
    answer: `You cannot be the trustee of your own MAPT if you want the assets removed from your countable resources for Medicaid purposes — retaining that level of control over the principal would cause Ohio Medicaid to treat the assets as still available to you. Common choices are an adult child, another trusted family member, or a professional corporate trustee. The trustee must be someone who will follow the trust's terms faithfully and not make unauthorized distributions of principal to you. Since you lose the right to demand the principal back, trustee selection is one of the most important decisions in MAPT planning.`,
  },
  {
    question: `Can I change my mind after I set up a MAPT?`,
    answer: `A MAPT is irrevocable by design — that is what makes it work for Medicaid planning. You cannot take the assets back, change the trust to make yourself a principal beneficiary, or revoke the trust unilaterally. This is the core trade-off: you give up control over the principal in exchange for Medicaid protection after five years. If your circumstances change dramatically — for example, if you recover from an illness and no longer expect to need Medicaid — the trust typically continues and the assets ultimately pass to your designated remainder beneficiaries. Court-ordered trust modifications may be possible in extreme circumstances under ORC 5804.12, but this is not a reliable or inexpensive escape hatch.`,
  },
  {
    question: `What is an income-only trust, and how is it different from a regular MAPT?`,
    answer: `Most MAPTs are structured as income-only trusts: the grantor (you) may receive all income generated by the trust assets — interest, dividends, rent — but cannot receive any distributions of principal. This structure is what makes the trust principal excluded from your countable Medicaid resources. If you retained the right to receive principal distributions, Medicaid would treat the trust principal as fully available to you and count it toward the $2,000 resource limit. The income you receive from the trust is counted as income for Medicaid eligibility purposes and must be contributed toward your cost of care if you are receiving Medicaid nursing facility benefits.`,
  },
  {
    question: `What is a Miller Trust (Qualified Income Trust) and how is it different from a MAPT?`,
    answer: `A Miller Trust (also called a Qualified Income Trust or QIT) is a completely different tool used when your monthly income exceeds Ohio's Medicaid income limit for nursing facility coverage (currently $2,829/month in 2024 for a single person). Ohio is an "income cap" state for nursing facility Medicaid, meaning applicants with income above the cap cannot qualify — unless their excess income is directed into a QIT each month. The QIT is an irrevocable trust into which you deposit your monthly income above the cap; those funds are then used to pay for your care. A MAPT deals with assets (what you own); a QIT deals with income (what you receive each month). Many clients need both.`,
  },
];

export default function MedicaidAssetProtectionTrustsPage() {
  return (
    <>
      <Breadcrumbs items={breadcrumbItems} />
      <PageHero
        title="Ohio Medicaid Asset Protection Trusts Lawyer"
        description="Protect your home and savings from Ohio Medicaid spend-down with a properly structured Medicaid Asset Protection Trust. Our Columbus elder law attorneys guide families through the five-year lookback, income-only trust design, and estate recovery protection under ORC 5163.21."
      />
      <section className="py-16 bg-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="prose prose-lg max-w-none">

            <h2 className="font-['Playfair_Display',_'Georgia',_serif] text-3xl font-bold text-gray-900 mb-6">
              Medicaid Asset Protection Trusts in Ohio: Protecting Your Assets Before You Need Long-Term Care
            </h2>
            <p className="font-['Inter',_'Arial',_sans-serif] text-gray-700 mb-6 leading-relaxed">
              The cost of long-term care in Ohio is substantial. Nursing facility care in the Columbus area averages $9,000 to $11,000 per month, and memory care and assisted living facilities charge comparable amounts. Without proper planning, a single year of nursing home care can deplete $100,000 to $130,000 in savings — wiping out assets that took a lifetime to accumulate. Ohio Medicaid — the jointly funded state-federal program that covers long-term care costs for eligible residents — requires applicants to have no more than $2,000 in countable resources as a single person before benefits begin. A Medicaid Asset Protection Trust (MAPT) is an irrevocable planning tool that, when established at least five years before applying for Medicaid, removes transferred assets from the countable resource calculation and shields them from Ohio\'s Medicaid estate recovery program. Jwayyed Law LLC advises clients throughout Columbus, Cincinnati, Dayton, and the surrounding Ohio communities on timely Medicaid planning, including the establishment and funding of MAPTs.
            </p>
            <p className="font-['Inter',_'Arial',_sans-serif] text-gray-700 mb-6 leading-relaxed">
              Ohio Medicaid for long-term care is administered under ORC Chapter 5163 and governed federally by 42 U.S.C. 1396 et seq. To qualify for nursing facility Medicaid as a single person, you must have no more than $2,000 in countable resources. Countable resources include bank accounts, CDs, stocks, bonds, non-primary-residence real estate, and most other financial assets. Exempt resources include your primary residence (while you or your spouse lives there), one vehicle, personal household goods, prepaid funeral arrangements, and a few other categories. Ohio Medicaid also imposes an income contribution requirement — most of your monthly income must be paid to the nursing facility as your "patient pay amount," with Medicaid covering the balance up to the Medicaid rate.
            </p>
            <p className="font-['Inter',_'Arial',_sans-serif] text-gray-700 mb-6 leading-relaxed">
              The five-year lookback period is the central legal constraint on MAPT planning. Under 42 U.S.C. 1396p(c), any transfer of assets for less than fair market value within 60 months of a Medicaid application will result in a penalty period — a period during which Medicaid will not pay for nursing facility care. The penalty period is calculated by dividing the value of the transferred assets by the average monthly cost of nursing care in Ohio (approximately $9,500 per month in 2024 for this calculation). A $190,000 home transfer, for example, could result in a 20-month penalty period. Critically, this penalty period does not begin until you would otherwise be eligible for Medicaid but for the transferred asset — so an applicant with $190,000 in transferred assets and no other resources could face a 20-month gap with no coverage and no assets to pay privately.
            </p>

            <h3 className="font-['Playfair_Display',_'Georgia',_serif] text-2xl font-bold text-gray-900 mt-10 mb-4">
              How a MAPT Is Structured: Income-Only Trust Design
            </h3>
            <p className="font-['Inter',_'Arial',_sans-serif] text-gray-700 mb-6 leading-relaxed">
              A MAPT is an irrevocable trust in which you transfer assets to the trust and name an independent trustee (typically an adult child or trusted third party) and remainder beneficiaries (your heirs). The defining structural feature is that you — as the grantor — cannot be a beneficiary of the trust\'s principal. If you retain the right to receive trust principal on demand, Ohio Medicaid will treat the trust as a revocable resource and count it toward your $2,000 limit.
            </p>
            <p className="font-['Inter',_'Arial',_sans-serif] text-gray-700 mb-6 leading-relaxed">
              Most MAPTs are structured as income-only trusts: the trust agreement gives you the right to receive all net income generated by trust assets — interest, dividends, rental income — but gives you no right to principal. This income stream is counted as your income for Medicaid purposes and must be applied toward your nursing facility cost of care if you are receiving Medicaid benefits. The principal, however, is no longer a countable resource once the five-year lookback period has expired. This means you can fund a MAPT with your home, a brokerage account, or a bank CD, continue to receive any interest or rent those assets generate, and eventually qualify for Medicaid without those assets counting against your eligibility.
            </p>
            <p className="font-['Inter',_'Arial',_sans-serif] text-gray-700 mb-6 leading-relaxed">
              Protecting the family home is one of the most common MAPT objectives for Ohio clients. While your primary residence is exempt from countable resources during your lifetime, it is subject to Ohio Medicaid estate recovery under ORC 5163.21 after your death. Ohio Medicaid can file a claim against your probate estate — including your home if it passes through probate — to recoup all Medicaid benefits paid on your behalf after age 55. By transferring the home to a MAPT more than five years before applying for Medicaid, you protect it from estate recovery because the home passes outside of your probate estate. Your heirs receive the home free of any Medicaid estate recovery claim.
            </p>

            <h3 className="font-['Playfair_Display',_'Georgia',_serif] text-2xl font-bold text-gray-900 mt-10 mb-4">
              Ohio Medicaid Estate Recovery, Spend-Down Alternatives, and Miller Trusts
            </h3>
            <p className="font-['Inter',_'Arial',_sans-serif] text-gray-700 mb-6 leading-relaxed">
              Even when a MAPT was not established years in advance, there are other Medicaid planning strategies available to Ohio residents facing an imminent nursing home admission. Spending down to the $2,000 resource limit through legitimate expenditures — prepaying funeral costs, paying off a mortgage, purchasing home modifications or medical equipment, or making gifts to adult children (with an understanding of the lookback implications) — can accelerate Medicaid eligibility. Purchasing a Medicaid-compliant immediate annuity can convert a countable asset into an income stream that is not a countable resource. Each of these strategies must be carefully evaluated in light of the lookback rules and your specific asset composition.
            </p>
            <p className="font-['Inter',_'Arial',_sans-serif] text-gray-700 mb-6 leading-relaxed">
              For applicants whose monthly income exceeds Ohio\'s income cap for nursing facility Medicaid ($2,829/month in 2024 for single individuals), a Qualified Income Trust (QIT) — also called a Miller Trust — is required. Each month, the applicant\'s income that exceeds the cap is deposited into the QIT, which then pays the nursing facility directly. The QIT does not involve the five-year lookback and is established quickly as part of the Medicaid application process. Unlike a MAPT (which is a pre-planning tool for assets), a QIT is an eligibility tool for income-over-limit situations.
            </p>
            <p className="font-['Inter',_'Arial',_sans-serif] text-gray-700 mb-8 leading-relaxed">
              Medicaid planning is among the most time-sensitive areas of elder law. The ideal time to establish a MAPT is at least five to ten years before you anticipate needing long-term care — while you are healthy enough to transfer assets and start the lookback clock. Waiting until a health crisis forces the issue often eliminates the MAPT option and leaves far fewer planning tools available. If you or a parent are in their 60s or 70s and have not yet addressed long-term care planning, now is the time to consult with a Medicaid planning attorney. Call Jwayyed Law LLC at (614) 285-5482 to schedule a consultation about protecting your assets with a MAPT.
            </p>

            <LocationsWeServe title="Medicaid Asset Protection Trusts" />

            <div className="grid sm:grid-cols-2 gap-4 mt-8 mb-8">
              <Link href="/trusts" className="block p-4 border border-gray-200 rounded-lg hover:border-[#b87333] hover:shadow-md transition-all font-medium text-gray-900 font-['Inter',_'Arial',_sans-serif]">
                All Trust Services
              </Link>
              <Link href="/trusts/irrevocable-trusts" className="block p-4 border border-gray-200 rounded-lg hover:border-[#b87333] hover:shadow-md transition-all font-medium text-gray-900 font-['Inter',_'Arial',_sans-serif]">
                Irrevocable Trusts
              </Link>
              <Link href="/other-services/estate-planning-wills" className="block p-4 border border-gray-200 rounded-lg hover:border-[#b87333] hover:shadow-md transition-all font-medium text-gray-900 font-['Inter',_'Arial',_sans-serif]">
                Estate Planning &amp; Wills
              </Link>
              <Link href="/trusts/revocable-living-trusts" className="block p-4 border border-gray-200 rounded-lg hover:border-[#b87333] hover:shadow-md transition-all font-medium text-gray-900 font-['Inter',_'Arial',_sans-serif]">
                Revocable Living Trusts
              </Link>
            </div>

          </div>
        </div>
      </section>
      <FAQ faqs={faqs} />
      <ContactCTA />
    </>
  );
}
